TM.BusinessCourses/TM.BusinessCourses/Models/Section.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TM.BusinessCourses.Models
{
    public class Section
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Course"), ForeignKey("course"), Required(ErrorMessage = "Course is required.")]
        public int? course_id { get; set; }

        [Display(Name = "Course")]
        public Course course { get; set; }

        [Display(Name ="Section"), Required(ErrorMessage = "Course Section is required.")]
        public int course_section { get; set; }   
        
        [ForeignKey("instructor"), Display(Name = "Instructor")]
        public int? instructor_id { get; set; }

        public Faculty instructor { get; set; }

        [ForeignKey("location"), Display(Name = "Location")]
        public int? location_id { get; set; }

        public Location location { get; set; }

        [Display(Name ="Meeting Days"), Required(ErrorMessage = "Meeting Days is required.")]
        public string days { get; set; }//"MTWRF, None"

        [Display(Name = "Start Date"), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true), Required(ErrorMessage = "Start Date is required.")]
        [DataType(DataType.Date)]
        public DateTime start_date { get; set; }

        [Display(Name = "End Date"), DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true), Required(ErrorMessage = "End Date is required.")]
        [DataType(DataType.Date)]
        public DateTime end_date { get; set; }

        [Display(Name ="Start Time"), DisplayFormat(DataFormatString = @"{0:hh\:mm}"), Required(ErrorMessage = "Start Time is required.")]
        [DataType(DataType.Time)]
        public TimeSpan start_time { get; set; }

        [Display(Name ="End Time"), DisplayFormat(DataFormatString = @"{0:hh\:mm}"), Required(ErrorMessage = "End Time is required.")]
        [DataType(DataType.Time)]
        public TimeSpan end_time { get; set; }

        [Display(Name ="Class Type"), Required(ErrorMessage = "Class Type is required.")]
        public string class_type { get; set; }//TAP, Undergrad

        [Display(Name ="Class Style"), Required(ErrorMessage = "Class Style is required.")]
        public string class_style { get; set; }//Online, Hybrid, Traditional

        [Display(Name = "Deleted")]
        public bool deleted { get; set; }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TM.BusinessCourses.Models;

namespace TM.BusinessCourses.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CoursesController : Controller
    {
        private TMBusinessCoursesContext db = new TMBusinessCoursesContext();

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.coordinator_id = new SelectList(db.Faculties, "id", "DropDown");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,course_name,course_no,coordinator_id")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Sections", "Home", new { id = course.id });
            }

            ViewBag.coordinator_id = new SelectList(db.Faculties, "id","DropDown", course.coordinator_id);
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.coordinator_id = new SelectList(db.Faculties, "id", "DropDown", course.coordinator_id);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,course_name,course_no,coordinator_id")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Sections", "Home", new { id = course.id });
            }
            ViewBag.coordinator_id = new SelectList(db.Faculties, "id","DropDown", course.coordinator_id);
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Include(c=>c.coordinator).Where(x=>x.id == id).First();
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Courses.Find(id).deleted = true;
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Restore(int id)
        {
            db.Courses.Find(id).deleted = false;
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TM.BusinessCourses.Models;


namespace TM.BusinessCourses.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private TMBusinessCoursesContext db = new TMBusinessCoursesContext();

        
        public ActionResult Index(string sortOrder, string search, string deleted)
        {
            ViewBag.deleted = deleted;
            ViewBag.search = search;
            ViewBag.NumberSortParm = String.IsNullOrEmpty(sortOrder) ? "num_desc" : "";
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";
            ViewBag.CoordSortParm = sortOrder == "Coord" ? "coord_desc" : "Coord";
            if (search != null)
            {
                var fa = db.Faculties.Where(x => x.email.Contains(search) || x.first_name.Contains(search) || x.last_name.Contains(search));
                var courses = db.Courses.Include(c => c.coordinator).Where(x => x.course_name.Contains(search) || x.course_no.Contains(search) || fa.Contains(x.coordinator));
                if (deleted == "" || deleted == null)
                    courses = courses.Where(x => x.deleted == false);
                else
                    courses = courses.Where(x => x.deleted == true);
                switch (sortOrder)
                {
                    case "num_desc":
                        courses = courses.OrderByDescending(s => s.course_no);
                        break;
                    case "Name":
                        courses = courses.OrderBy(s => s.course_name);
                        break;
                    case "name_desc":
                        courses = courses.OrderByDescending(s => s.course_name);
                        break;
                    case "Coord":
                        courses = courses.OrderBy(s => s.coordinator.first_name);
                        break;
                    case "coord_desc":
                        courses = courses.OrderByDescending(s => s.coordinator.first_name);
                        break;
                    default:
                        courses = courses.OrderBy(s => s.course_no);
                        break;
                }
                ViewBag.courses = courses.ToList();
                return View();
            }
            else
            {
                var courses = db.Courses.Include(c=>c.coordinator);
                if (deleted == "" || deleted == null)
                    courses = courses.Where(x => x.deleted == false);
                else
                    courses = courses.Where(x => x.deleted == true);
                switch (sortOrder)
                {
                    case "num_desc":
                        courses = courses.OrderByDescending(s => s.course_no);
                        break;
                    case "Name":
                        courses = courses.OrderBy(s => s.course_name);
                        break;
                    case "name_desc":
                        courses = courses.OrderByDescending(s => s.course_name);
                        break;
                    case "Coord":
                        courses = courses.OrderBy(s => s.coordinator.first_name);
                        break;
                    case "coord_desc":
                        courses = courses.OrderByDescending(s => s.coordinator.first_name);
                        break;
                    default:
                        courses = courses.OrderBy(s => s.course_no);
                        break;
                }
                ViewBag.courses = courses.ToList();
                return View();
            }
                //courses.AddRange(db.Courses.Where(x => db.Faculties.Where(y=>y.id == x.coordinator_id == search));            
        }

        public ActionResult Sections(string id, string sortOrder, string deleted)
        {
            if (id == null)
                id = "1";
            ViewBag.CourseSortParm = String.IsNullOrEmpty(sortOrder) ? "course_desc" : "";
            ViewBag.InstructorSortParm = sortOrder == "Instr" ? "instr_desc" : "Instr";
            ViewBag.LocationSortParm = sortOrder == "Locat" ? "locat_desc" : "Locat";
            ViewBag.course = db.Courses.Include(c => c.coordinator).Where(x => x.id.ToString() == id).First();
            var section = db.Sections.Include(s => s.course).Include(s => s.course.coordinator).Include(s => s.instructor).Include(s => s.location).Where(x => x.course_id.ToString() == id);
            if (deleted == "" || deleted == null)
                section = section.Where(x => x.deleted == false);
            else
                section = section.Where(x => x.deleted == true);
            switch (sortOrder)
            {
                case "course_desc":
                    section = section.OrderByDescending(x => x.course.course_name);
                    break;
                case "Instr":
                    section = section.OrderBy(x => x.instructor.last_name);
                    break;
                case "instr_desc":
                    section = section.OrderByDescending(x => x.instructor.last_name);
                    break;
                case "Locat":
                    section = section.OrderBy(x => x.location.name);
                    break;
                case "locat_desc":
                    section = section.OrderByDescending(x => x.location.name);
                    break;
                default:
                    section = section.OrderBy(x => x.course.course_name);
                    break;
            }
            ViewBag.deleted = deleted;
            return View(section.ToList());
        }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TM.BusinessCourses.Models;

namespace TM.BusinessCourses.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SectionsController : Controller
    {
        private TMBusinessCoursesContext db = new TMBusinessCoursesContext();

        // GET: Sections/Create
        public ActionResult Create(string id)
        {
            ViewBag.course_id = new SelectList(db.Courses.Where(x=>x.id.ToString() == id), "id", "course_name");
            ViewBag.instructor_id = new SelectList(db.Faculties, "id", "DropDown");
            ViewBag.location_id = new SelectList(db.Locations, "id", "name");
            ViewBag.id = id;
            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,course_id,course_section,instructor_id,location_id,start_date,end_date,days,start_time,end_time,class_type,class_style")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("Sections", "Home", new { id = section.course_id });
            }

            ViewBag.course_id = new SelectList(db.Courses.Where(x=>x.id == section.course_id), "id", "course_name", section.course_id);
            ViewBag.instructor_id = new SelectList(db.Faculties, "id", "DropDown", section.instructor_id);
            ViewBag.location_id = new SelectList(db.Locations, "id", "name", section.location_id);
            return View(section);
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            ViewBag.course_id = new SelectList(db.Courses.Where(x=>x.id == section.course_id), "id", "course_name");
            ViewBag.instructor_id = new SelectList(db.Faculties, "id", "DropDown", section.instructor_id);
            ViewBag.location_id = new SelectList(db.Locations, "id", "name", section.location_id);
            return View(section);
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,course_id,course_section,instructor_id,location_id,start_date,end_date,days,start_time,end_time,class_type,class_style")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Sections", "Home", new { id = section.course_id });
            }
            ViewBag.course_id = new SelectList(db.Courses.Where(x=>x.id == section.course_id.Value), "id", "course_name", section.course_id);
            ViewBag.instructor_id = new SelectList(db.Faculties, "id", "DropDown", section.instructor_id);
            ViewBag.location_id = new SelectList(db.Locations, "id", "name", section.location_id);
            return View(section);
        }

        // GET: Sections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Include(s=>s.course).Include(s=>s.instructor).Include(s=>s.course.coordinator).Include(s=>s.location).Where(x=>x.id == id).First();
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Sections.Find(id).deleted = true;
            db.SaveChanges();
            return RedirectToAction("Sections", "Home", new { @id = db.Sections.Find(id).course_id });
        }

        public ActionResult Restore(int id)
        {
            db.Sections.Find(id).deleted = false;
            db.SaveChanges();
            return RedirectToAction("Sections", "Home", new { @id = db.Sections.Find(id).course_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TM.BusinessCourses/TM.BusinessCourses/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TM.BusinessCourses/TM.BusinessCourses/Views/Home/Index.cshtml
@model TM.BusinessCourses.Models.Course

@{
    ViewBag.Title = "Home Page";
}
<style>
    .btn {
        background: #263776;
        color: #fff;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

        .btn:hover {
            color: #263776;
            background: #C5C5C5;
        }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Search</h2>
        <input type="text" id="search" , name="search" value="@ViewBag.search" />
        <input type="text" id="deleted" , name="deleted" value="@ViewBag.deleted" hidden />
        <input type="submit" value="Search" class="btn btn-default" />
    </div>
}
<br />
@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Add Course", "Create", "Courses", null, new { @class = "btn btn-default" })
        @if (ViewBag.deleted == null || ViewBag.deleted == "")
        {
        @Html.ActionLink("Deleted Courses", "Index", new { @deleted = "true"}, new { @class = "btn btn-default" })
        }
        else
        {
        @Html.ActionLink("Active Courses", "Index", null, new { @class = "btn btn-default" })
        }
    </p>
}
<hr />


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Course Name", "Index", new { sortOrder = @ViewBag.NameSortParm, search = ViewBag.search })
        </th>
        <th>
            @Html.ActionLink("Course Number", "Index", new { sortOrder = @ViewBag.NumberSortParm, search = ViewBag.search })
        </th>
        <th>
            @Html.ActionLink("Coordinator", "Index", new { sortOrder = @ViewBag.CoordSortParm, search = ViewBag.search })
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in ViewBag.courses)
    {
        <tr>
            <td>
                <a href="~/Home/Sections/@item.id">
                    @item.course_name
                </a>
            </td>
            <td>
                @item.course_no
            </td>
            <td>
                @item.coordinator.first_name @item.coordinator.last_name - @item.coordinator.email
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    if (ViewBag.deleted == null || ViewBag.deleted == "")
                    {
                        @Html.ActionLink("Delete", "Delete", "Courses", new { id = item.id }, new { @class = "btn btn-default" })
                    }
                    else
                    {
                        @Html.ActionLink("Restore", "Restore", "Courses", new { id = item.id }, new { @class = "btn btn-default" })
                    }
                }
            </td>
        </tr>
    }
</table>

TM.BusinessCourses/TM.BusinessCourses/Views/Home/Sections.cshtml
@model IEnumerable<TM.BusinessCourses.Models.Section>

@{
    ViewBag.Title = "Index";
}
<style>
    .btn {
        background: #263776;
        color: #fff;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

        .btn:hover {
            color: #263776;
            background: #C5C5C5;
        }
</style>
<h2>@ViewBag.course.course_no - @ViewBag.course.course_name</h2>
<h3>Content Coordinator: @ViewBag.course.coordinator.first_name @ViewBag.course.coordinator.last_name - <a href="mailto:@ViewBag.course.coordinator.email">@ViewBag.course.coordinator.email</a></h3>
@if (User.IsInRole("Admin"))
{
    <p>@Html.ActionLink("Edit Course", "Edit", "Courses", new { id = ViewBag.course.id }, new { @class = "btn btn-default" })</p>
    <p>@Html.ActionLink("Add Section", "Create", "Sections", new { @id = ViewBag.course.id }, new { @class = "btn btn-default" })</p>
    if (ViewBag.deleted == null || ViewBag.deleted == "")
    {
        @Html.ActionLink("Deleted Sections", "Sections", new { @deleted = "true", @id = ViewBag.course.id }, new { @class = "btn btn-default" })
    }
    else
    {
        @Html.ActionLink("Active Sections", "Sections", new { @id = ViewBag.course.id, @deleted = "" }, new { @class = "btn btn-default" })
    }
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.course_section)
        </th>
        <th>
            @Html.ActionLink("Instructor", "Sections", new { sortOrder = @ViewBag.InstructorSortParm })
        </th>
        <th>
            @Html.ActionLink("Location", "Sections", new { sortOrder = @ViewBag.LocationSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.start_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.end_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.days)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.start_time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.end_time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.class_type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.class_style)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.course_section)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.instructor.first_name) @Html.DisplayFor(modelItem => item.instructor.last_name) - @Html.DisplayFor(modelItem => item.instructor.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.location.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.start_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.end_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.days)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.start_time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.end_time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.class_type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.class_style)
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "Edit", "Sections", new { id = item.id }, new { @class = "btn btn-default" })
                    if (ViewBag.deleted == null || ViewBag.deleted == "")
                    {
                        @Html.ActionLink("Delete", "Delete", "Sections", new { id = item.id }, new { @class = "btn btn-default" })
                    }
                    else
                    {
                        @Html.ActionLink("Restore", "Restore", "Sections", new { id = item.id }, new { @class = "btn btn-default" })
                    }
                }
            </td>

        </tr>
    }

</table>

<p>
    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
</p>