TM.BusinessCourses/TM.BusinessCourses/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TM.BusinessCourses.Models;

namespace TM.BusinessCourses.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FacultiesController : Controller
    {
        private TMBusinessCoursesContext db = new TMBusinessCoursesContext();

        // GET: Faculties
        public ActionResult Index(string sortOrder, string deleted, string search)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.FirstSortParm = sortOrder == "First" ? "first_desc" : "First";
            List<Faculty> fac;
            if (deleted == null || deleted == "")
            {
                var faculty = db.Faculties.Where(x => x.deleted != true);
                if (search != "" && search != null)
                    faculty = faculty.Where(x => x.first_name.Contains(search) || x.last_name.Contains(search) || x.email.Contains(search));
                switch (sortOrder)
                {
                    case "name_desc":
                        faculty = faculty.OrderByDescending(s => s.last_name);
                        break;
                    case "First":
                        faculty = faculty.OrderBy(s => s.first_name);
                        break;
                    case "first_desc":
                        faculty = faculty.OrderByDescending(s => s.first_name);
                        break;
                    default:
                        faculty = faculty.OrderBy(s => s.last_name);
                        break;
                }
                fac = faculty.ToList();
            }
            else
            {
                var faculty = db.Faculties.Where(x => x.deleted == true);
                if (search != "" && search != null)
                    faculty = faculty.Where(x => x.first_name.Contains(search) || x.last_name.Contains(search) || x.email.Contains(search));
                switch (sortOrder)
                {
                    case "name_desc":
                        faculty = faculty.OrderByDescending(s => s.last_name);
                        break;
                    case "First":
                        faculty = faculty.OrderBy(s => s.first_name);
                        break;
                    case "first_desc":
                        faculty = faculty.OrderByDescending(s => s.first_name);
                        break;
                    default:
                        faculty = faculty.OrderBy(s => s.last_name);
                        break;
                }
                fac = faculty.ToList();
            }
            ViewBag.deleted = deleted;
            ViewBag.search = search;
            return View(fac);
        }

        // GET: Faculties/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,first_name,last_name,email")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                db.Faculties.Add(faculty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,first_name,last_name,email,deleted")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(faculty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Faculties.Find(id).deleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeletedUsers()
        {
            return View(db.Faculties.Where(x => x.deleted == true));
        }
        

        public ActionResult Restore(int id)
        {
            db.Faculties.Find(id).deleted = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TM.BusinessCourses.Models;

namespace TM.BusinessCourses.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LocationsController : Controller
    {
        private TMBusinessCoursesContext db = new TMBusinessCoursesContext();

        // GET: Locations
        public ActionResult Index(string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var locations = from s in db.Locations
                          select s;
            switch (sortOrder)
            {
                case "name_desc":
                    locations = locations.OrderByDescending(s => s.name);
                    break;
                default:
                    locations = locations.OrderBy(s => s.name);
                    break;
            }
            return View(locations.ToList());
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TM.BusinessCourses/TM.BusinessCourses/Views/Admin/Edit.cshtml
@model TM.BusinessCourses.Models.ApplicationUser

@{
    ViewBag.Title = "Edit";
}
<style>
    .btn {
        background: #263776;
        color: #fff;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

        .btn:hover {
            color: #263776;
            background: #C5C5C5;
        }
</style>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ApplicationUser</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="checkAdmin" class="control-label col-md-2">Is Admin: </label>
        <div class="col-md-10">
            @if (ViewBag.isAdmin == true)
            {
                @Html.CheckBox("checkAdmin", true)
            }
            else
            {
                @Html.CheckBox("checkAdmin", false)
            }
        </div>
    </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageUsers", null, new { @class = "btn btn-default" })
</div>

TM.BusinessCourses/TM.BusinessCourses/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    .btn {
        background: #263776;
        color: #fff;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

        .btn:hover {
            color: #263776;
            background: #C5C5C5;
        }
</style>
<h2>Index</h2>

<p>@Html.ActionLink("Manage Users", "ManageUsers", null, new { @class = "btn btn-default" })</p>
<p>@Html.ActionLink("Manage Faculty", "Index", "Faculties", null, new { @class = "btn btn-default" })</p>
<p>@Html.ActionLink("Manage Location", "Index", "Locations", null, new { @class = "btn btn-default" })</p>

TM.BusinessCourses/TM.BusinessCourses/Views/Admin/ManageUsers.cshtml
@model IEnumerable<TM.BusinessCourses.Models.ApplicationUser>
@{
    ViewBag.Title = "ManageUsers";
}

<h2>ManageUsers</h2>

<style>
    .btn {
        background: #263776;
        color: #fff;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

        .btn:hover {
            color: #263776;
            background: #C5C5C5;
        }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h2>Search</h2>
    <input type="text" id="search" , name="search" value="@ViewBag.search" />
    <input type="submit" value="Search" class="btn btn-default" />
</div>
}
<p>@Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })</p>
<table class="table">
    <tr>
        <th>
            UserName
        </th>
        <th>
            Email
        </th>
        <th>
            Admin
        </th>
        <th>

        </th>
    </tr>
    
@foreach (TM.BusinessCourses.Models.ApplicationUser user in Model)
{

<tr>
    <td>
        @user.UserName
    </td>
    <td>
        @user.Email
    </td>
    <td>
        @if (user.Roles.Where(x => x.RoleId == ViewBag.adminID).Count() > 0)
        {
            <input type="checkbox" name="admin" disabled checked>
        }
        else
        {
            <input type="checkbox" name="admin" disabled>
        }
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = user.Id }, new { @class = "btn btn-default" })
    </td>
</tr>
}
</table>